---
# defaults file for php
PROJECT_ROOT: "/var/www"
PROJECT_PHP_VERSION: "7.2"

php_session_save_handler: "memcached"
php_session_save_path: "127.0.0.1:11212"

php_cli_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_cli_memory_limit: "-1"
php_cli_expose_php: "On"
php_cli_display_errors: "Off"
php_cli_display_startup_errors: "Off"
php_cli_max_execution_time: "60"
php_cli_max_input_time: "90"
php_cli_upload_max_filesize: "1024M"
php_cli_post_max_size: "1024M"

php_fpm_emergency_restart_threshold: 4
php_fpm_emergency_restart_interval: 60
php_fpm_process_control_timeout: 10

php_fpm_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_fpm_memory_limit: "256M"
php_fpm_expose_php: "Off"
php_fpm_display_errors: "Off"
php_fpm_display_startup_errors: "Off"
php_fpm_max_execution_time: "60"
php_fpm_max_input_time: "90"
php_fpm_upload_max_filesize: "1024M"
php_fpm_post_max_size: "1024M"

php_fpm_www_additional:
  - filename: www_additional
    name: www
    listen.owner: vagrant
    listen.group: vagrant
    listen.mode: '0660'
    pm.max_children: 50
