---
- import_playbook: common.yml

# This is a setup for vagrant host, inherits from all
- hosts: default, localhost
  become: yes
  roles:
    - kernel
    - { role: 'memcached', tags: 'memcached' }
    - nodejs
    - varnish
    - php
    - { role: composer, use_composer_no_dev: no, install_vendors: false }
    - { role: 'rabbitmq', tags: 'rabbitmq' }
    - { role: 'mysql', tags: 'mysql' }
#    - { role: 'users', tags: 'users' }
    - { role: 'csync2', tags: 'csync2' }
#    - { role: mailcatcher }

  tasks:
    - name: restart Varnish
      service: name=varnish state=restarted
      become: yes
